### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by stants12** [Valacdi/rePeterGriffinAlert#1]
Hello.
After using this app for 2 hours I have found some bugs with it.
The main issue right now is the window can be re-sized to any form. This is something that should not be possible.
![image](https://user-images.githubusercontent.com/12599845/111072982-9d844280-84e5-11eb-8cc7-64e31e6df553.png)

Another issue is there's a default Forms icon which should not be visible. 
![image](https://user-images.githubusercontent.com/12599845/111072999-ad038b80-84e5-11eb-9b11-5a7348e1a7cd.png)

The minimize and maximize buttons should not be there at all. 
![image](https://user-images.githubusercontent.com/12599845/111073023-c1e01f00-84e5-11eb-80ea-ed99d82651fe.png)

Lastly, you are using an incorrect 32x32 image of Peter Griffin's head. I hope everything will be fixed very soon as I'm looking forward to be using this every day.

**Comment by Valacdi** [comment]
Hello, Mawskeeto1223

Thank you for being interested in our newly baked project! The bugs you mentioned are already fixed in our debug version, expect a 1.1 release soon!
